version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-smart_gkh}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 5

  accounts-service:
    build:
      context: ./accounts_service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-postgres}
      - DATABASE_USER=${POSTGRES_USER:-postgres}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DATABASE_NAME=${DATABASE_NAME:-smart_gkh}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    
  payment-service:
    build:
      context: ./payment_service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-postgres}
      - DATABASE_USER=${POSTGRES_USER:-postgres}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DATABASE_NAME=${DATABASE_NAME:-smart_gkh}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - PAYMENT_MOCK_SERVICE_URL=http://payment-mock-service:8000
    depends_on:
      postgres:
        condition: service_healthy
      payment-mock-service:
        condition: service_started
    restart: unless-stopped

  payment-mock-service:
    container_name: payment-mock-service
    build:
      context: ./payment_mock_service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    
  minio:
    container_name: s3-minio
    restart: always
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9011:9001"
      - "9010:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
